Feature/issue67　/cocktail/{id} カクテルの画像が全部スプライトになってるので修正
randombar164/ouchi_bar pull request #75
Opened 2022-02-17 08:52 UTC by akaishikiso

プッシュした後で申し訳ないのですが、なぜか変更がローカルでみられないので、もしかしたら変なコード書いてるかもしれないです。

ご確認よろしくお願いします！

2022-02-17 09:03 UTC, H0R15H0 requested changes
最初に伝えておくべきでしたが、DrinkMethodは全部で4つあるみたいです🙇‍♂️
```
DrinkMethod.pluck(:name)
=> ["Build", "Shake", "Blend", "Stir"]
```

2022-02-17 09:12 UTC, H0R15H0 commented on frontend/src/pages/cocktail-recipe/[id].page.tsx
> +                <CocktailImg recipe={useGetRecipe(cocktailId)} />
細かいところではあるけど21行目で`useGetRecipe`呼び出しているからそのインスタンス(`recipe`)を使うとAPI叩く回数減らせていいかもね！

2022-02-17 09:49 UTC, akaishikiso commented on frontend/src/pages/cocktail-recipe/[id].page.tsx
> +                <CocktailImg recipe={useGetRecipe(cocktailId)} />
recipeを使うというのは、`<img src="/{recipe.drinkMethod}.png/>"`みたいにするということですか？
自分でも書いていて冗長だなーまとめられそうだなーっとは思っていたんですけど、「呼び出した`useGetRecipe`のインスタンス`recipe`を使う」というのがよくわかっていないです…

2022-03-05 21:29 UTC, Hide-nu commented on frontend/src/components/CocktailImg.tsx
> +      if ({recipe.drinkMethod}="Build")
recipe.drinkMethodは10, 12行目でも同様に使っているので，5,6行目の間で
`const drinkMethod = recipe.drinkMethod`
とまとめてもいいかもしれないです！

2022-03-05 21:29 UTC, Hide-nu commented on frontend/src/components/CocktailImg.tsx
> +      {<img src="/blend.png" width={49} height={177} alt="ブレンド" />}
JSX内での条件分岐(if文等)の書き方は以下の記事を参考にしてみてください！
https://qiita.com/akifumii/items/c302fdc633d8eba2af0a

2022-03-08 00:22 UTC, akaishikiso commented
@Hide-nu @H0R15H0 レビューしてくださってありがとうございます！修正してみました！再度ご確認お願いします！

2022-05-13 12:20 UTC, merged